[package]
name = "escpctl"
version = "0.1.0"
authors = ["Taras Zakharchenko <taras.zakharchenko@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iconv = "^0.1.1"